### ISSUE TITLE
dnsfilter library

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/DnsLibs#1]
* Memory-efficient
* Must support hosts files syntax
* Supports a limited set of Adblock-style modifiers: `badfilter`, `important`
* "Just domains" syntax 

It makes sense to take something from this library:
https://github.com/AdguardTeam/urlfilter

Test filter lists:
* https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/gh-pages/Filters/filter.txt
* https://pgl.yoyo.org/
* https://energized.pro/

**Comment by sxgunchenko** [comment]
dns-libs/pull-requests/3
