### ISSUE TITLE
Increase DNS timeout for DnsProxy.testUpstream

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/DnsLibs#112]
It is possible that the server response is rather slow (i've seen cases with up to 10 seconds) so it's okay to use a high timeout.

Also, it'd be better to request `ipv4only.arpa` instead of some Google domains which might be blocked in some geos.

**Comment by ngorskikh** [comment]
`testUpstream` accepts full upstream settings, including timeout :) The idea is that the same settings should be passed to `testUpstream` that would be used to initialize the proxy. And we are already using `ipv4only.arpa` as the domain for the test query :)

**Comment by ngorskikh** [comment]
Oh, I see the problem: there's an IPv6 "connectivity check" that's actually trying to do a DNS exchange over UDP over IPv6.
