### ISSUE TITLE
"ttp" rule would block access to many domains

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/DnsLibs#118]
https://github.com/AdguardTeam/AdGuardDNS/issues/182

**Comment by sfionov** [comment]
Basically we apply "exact match" for string without | and ^, but they are also checked if they are domains.

We may allow domains without dots in such cases.

**Comment by ameshkov** [comment]
I mean `ttp` would match `example.org` that does not have the `ttp` substring in it.

**Comment by ngorskikh** [comment]
Couldn't reproduce with `example.org`. However, `ttp` is interpreted as a pattern, not an exact domain name, and anything with `ttp` in it (including in CNAME) matches. Fixed in dns-libs/pull-requests/319
