### ISSUE TITLE
router.asus.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/DnsLibs#122]
@adguard-bot commented on [Sat Sep 11 2021](https://github.com/AdguardTeam/AdguardFilters/issues/94417)

### Issue URL (Incorrect Blocking)
 [http://router.asus.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=http%3A%2F%2Frouter.asus.com)
### Comment
> I couldn't figure out why I couldn't log into my new router.  Once I disabled the AdGuard VPN the router  loads perfectly fine

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/W3N06aj.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/9G8j1Xe.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 11
AdGuard product: | AdGuard for Android v3.6.2 (23)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | server: `System`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>EasyList, <br/>Peter Lowe's Blocklist, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Fanboy's Annoyances, <br/>Web Annoyances Ultralist, <br/>EasyList Cookie List, <br/>I don't care about cookies, <br/>Adblock Warning Removal List<br/><br/><b>Security:</b><br/>Spam404, <br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

**Comment by nightznero** [comment]
Logs been sent a 10days without any replay. From menu in app,I got my ticket numbers,after 3days I sent a question what is going with my ticket but till day I didn't get any answer and still dns doesn't work properly

**Comment by Chinaski1** [comment]
@nightznero 

Sorry for the late reply.
We wanted to get to the bottom of your issue, but I can't find the logs you sent.

Could you please resend them to devteam@adguard.com so we can investigate further?

**Comment by nightznero** [comment]
@Chinaski1 done,I added a ticket number in mail cause on ticket I post logs from nightly channel and now from relase. Both have same issue but mby it's help somehow

**Comment by Chinaski1** [comment]
We got the logs, thank you.

As soon as there are any recommendations I will let you know

**Comment by nightznero** [comment]
Is there any news about my case cause it's been a whole month without any contact from Support?
