### ISSUE TITLE
ncvr2.kdca.go.kr

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/DnsLibs#124]
Tracking fix for affected platforms:
* [x] [Android](https://github.com/AdguardTeam/AdguardForAndroid/issues/3984) -- Fixed in 3.6.5 beta 1
* [ ] [iOS](https://github.com/AdguardTeam/AdguardForiOS/issues/1768) -- Planned for v4.4

@adguard-bot commented on [Mon Aug 16 2021](https://github.com/AdguardTeam/AdguardFilters/issues/91182)

### Issue URL (Incorrect Blocking)
 [https://ncvr2.kdca.go.kr/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fncvr2.kdca.go.kr%2F)
### Comment
> 한국 질졍관리청임.. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Dgw699d.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/74qBf3t.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 10
AdGuard product: | AdGuard for Android v4.0 nightly 22 (63)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | server: `https://dns.cloudflare.com/dns-query`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Language-specific:</b><br/>List-KR, <br/>YousList
Userscripts: | disabled

---

@Apious commented on [Thu Sep 30 2021](https://github.com/AdguardTeam/AdguardFilters/issues/91182#issuecomment-930677579)

still blocked reopen to fix

**Comment by sfionov** [comment]
Transferred to DnsLibs as a more suitable repo

**Comment by Apious** [comment]
still blocked 
are you kidding me?
almost korean issue about not open this site by adguard dns blocked

what's going on?

i added my filter as myself
@@||ncvr2.kdca.go.kr

**Comment by piquark6046** [comment]
@Apious 
Please read https://github.com/AdguardTeam/DnsLibs/issues/124#issuecomment-932943336.

**Comment by Apious** [comment]
i hope it will be fixed ASAP.

**Comment by ameshkov** [comment]
Closing as it duplicates https://github.com/AdguardTeam/AdguardForiOS/issues/1768
