### ISSUE TITLE
HTTP/3 support for DNS-over-HTTPS (DNS-over-HTTP/3, DoH3)

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/DnsLibs#131]
Hello,

unfortunately, I could not find any detailed information about the status of DNS-over-HTTPS with HTTP/3 (DNS-over-HTTP/3, DoH3) support here or on the forum. All I know is that filtration engine are now forcibly downgrading the connection protocol to HTTP/2😟

So please add DoH3 support in future releases for all applications with the DNS encryption and filtration🙂

Thank you.
Best regards!🎁

**Comment by ammnt** [comment]
Any update of this? HTTP3 support for NGINX is coming soon!🎉

**Comment by sfionov** [comment]
We should do three things here:
1) Flag to enable HTTP/3
2) Make a research which HTTP version choosing algorithm cURL uses, it should match Chrome's. If doesn't match, check if it is implemented correctly.
3) Add h3:// protocol to force HTTP/3 even if HTTP/3 support is not enabled for all upstreams.

**Comment by GiddyGoatGaming** [comment]
Now it’s just a matter of waiting for dnslib’s to be updated for the platforms

**Comment by zubrRB** [comment]
![-](https://user-images.githubusercontent.com/50718960/220139281-32121f6a-cb7d-4e25-87bd-17d6d9fa1184.png)

**Comment by SpencerIsGiddy** [comment]
I find it disappointing that the newly released adguard iOS 4.4.6 only supports dnslib v2.0.75. I hope they can update dnslib soon to support DoH3 because it was introduced in the soon after released dnslib v2.1.3
