### ISSUE TITLE
Try to integrate CURL with our socket abstractions

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/DnsLibs#134]

**Comment by ngorskikh** [comment]
I think it's just better and simpler to replace cURL with `http2_session`, maybe even already as part of converting to asynchronous model.

**Comment by sfionov** [comment]
This solution will conflict with task HTTP/3 (#131) and HTTP/1.1 support.

cURL is relatively good abstraction over HTTP protocols, that's why it is good idea to keep it for DoH :)

**Comment by sfionov** [comment]
Unfortunately, it is impossible without heavy patching
