### ISSUE TITLE
Many DNS requests in short time cause problem with internet connection

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/DnsLibs#135]
Steps to reproduce
1. Enable DNS Protection in AdGuard for Windows app
2. Run this program - https://www.grc.com/dns/benchmark.htm

After a while there is a problem with internet connection and opening any website causes that `DNS_PROBE_FINISHED_NO_INTERNET` error is displayed.

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/149204637-4e5fbd28-3618-466b-87fe-94b5c60eb7da.png)

![image](https://user-images.githubusercontent.com/29142494/149204891-ce7f468f-eb64-458f-9433-5c46de840cf7.png)

</details>

I have to disable AdGuard protection to fix this problem.

If I'm not wrong, it's not a new issue and the same problem occurs with previous version of AdGuard for Windows app.

AdGuard for Windows version 7.9 nightly 4 (build 3793, CL 1.9.5)

**Comment by sfionov** [comment]
@AdamWr What DNS upstream did you use?

**Comment by AdamWr** [comment]
As I recall, in AdGuard settings I had DNS set to `System default` and in system settings I had Cloudflare DNS (`1.1.1.1`).

By the way, I cannot reproduce this issue with latest nightly build version 7.13 nightly 2 (build 4183, CL 1.11.44), so I think that it has been fixed.
