### ISSUE TITLE
ld: warning: linking against a dylib which is not safe for use in application extensions

### ISSUE THREAD

**Issue by imranime** [AdguardTeam/DnsLibs#136]
Getting this warning when trying to link the AGDnsProxy.framework in iOS NetworkExtension PacketTunnelProvider

ld: warning: linking against a dylib which is not safe for use in application extensions: ........./Build/Products/Debug-iphoneos/AGDnsProxy.framework/AGDnsProxy

**Comment by sfionov** [comment]
That actually doesn't deny it to pass Apple review but we will look if any incompatible symbols are linked
