### ISSUE TITLE
Exclusion list for DNS not working

### ISSUE THREAD

**Issue by ep0ns** [AdguardTeam/DnsLibs#144]
I am using Adguard for Windows v7.9.1  and have enabled the DNS filter. I can't establish RDP connections to devices in company network.

RDP server1.internal.com

I have added *.internal.com to the DNS exclusion list but RDP says that server1.internal.com can't be found. Once Adguard DNS filter is disabled, it's working perfectly.

**Comment by maxikuzmin** [comment]
@ep0ns did you send the logs?

**Comment by maxikuzmin** [comment]
@ep0ns ping

**Comment by ep0ns** [comment]
@maxikuzmin Meanwhile I posted the issue in AdguardForWindows as issue 4239. I submitted the logs.

**Comment by maxikuzmin** [comment]
@ep0ns  Issue [#4239](https://github.com/AdguardTeam/AdguardForWindows/issues/4239) at work. Duplicate off.
