### ISSUE TITLE
Enabling DNS Protection slows down DNS requests

### ISSUE THREAD

**Issue by trparky** [AdguardTeam/DnsLibs#187]
### AdGuard version

7.12

### Browser version

Microsoft Edge 109.0.1518.70

### OS version

Windows 11 22H2 (22621.1194)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter

### Issue Details

Enabling DNS Protection slows down DNS requests by a huge amount.

**Comment by Aydinv13** [comment]
@Morku Hi again!

We are already fixing it. Could you clarify one more thing:

>I can totally agree to this. It happens on any device I use. 

Do you mean any Windows device?

**Comment by trparky** [comment]
God, I can't believe that this isn't fixed yet. And as you said, having this enabled by default is like suicide for AdGuard. I can't imagine how the people who don't know how to troubleshoot issues like this are thinking, they must be thinking AdGuard is a piece of crap and rightfully so.

Good God guys, you might as well have shot yourself in the foot here.

**Comment by trparky** [comment]
> After Nightly 4 was released, I just thought to give another try. Sure, it still not have a Resolved tag, but it should have IMO an high priority. No one is assigned here.
> 
> Using DNS module is still completely unusable. Making this option On as Default is doing a suicide for the program and new users who will quickly jump back to uBlock.
> 
> Another ~DNS hell~ test is https://www.bild.de/ Let's see how long it takes until the Anti Adblock page is fully loaded:
> 
>   And this is one of the better run. Sometimes it even takes 20-30 seconds until the page is even showing something.
> 
> And to compare, without DNS module:
> 
>   For the test, I have always used a clean browser profile with cleared cache and Cookies and also run ipconfig /flushdns previously.
> 
> I have sent you another Logfile after doing that test to [devteam@adguard.com](mailto:devteam@adguard.com)

Wow, just wow. That makes it even worse in terms of showing just how bad DNS filtering being enabled causes even the most capable high-speed Internet connection look like dial-up.

**Comment by trparky** [comment]
> @trparky This task has highest priority for Win 7.13 release and we are working on it.

Yeah, but in the meantime put out a interim release to turn off DNS Filtering on existing installations or all you guys are going to have left after shooting yourselves in the foot is a bloody stump.

**Comment by Aydinv13** [comment]
@trparky @Morku 

could you check the newest [nightly](https://agrd.io/windows_nightly) build?

**Comment by trparky** [comment]
@Morku, do you mind being the lab rat?

**Comment by Morku** [comment]
@Aydinv13 
Looks fine so far from my first test on Desktop, Laptop and virtual machine :)
I used the default setting.
I didn't encounter any abnormal delay or even timeout in the 2 hours of testing.

However, on my 13 years old laptop there is a little slowdown noticable with DNS module. But because of age and lack of power thats the way.

I don't want conclude for final that the issue is resolved, because I can't test another internet connection when once again I had big issues with Beta 2. But for now, it looks resolved for me.

**Comment by adbuker** [comment]
@Morku , nice to read. Issues with the Beta 2 are expectable, because it hasn't the fix

**Comment by trparky** [comment]
I'd say the issue has been solved with DNS Protection. Perhaps the only thing I could suggest at this point is that any and all AdGuard related processed are routed to the P-Cores as versus E-Cores on these stupid hybrid Intel chips.
