### ISSUE TITLE
Basic auth for DoH endpoints

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/DnsLibs#189]
Hello,

please consider to add support of basic auth function for DoH endpoints. Something like that:
`https://login:password@dns.example.com/dns-query/device1`

Thank you.
Best regards!

**Comment by sfionov** [comment]
Good idea, we'll consider it.

**Comment by ameshkov** [comment]
Besides `https://login:password@dns.example.com/dns-query/device1`, we should also allow specifying `user:password` in SDNS URLs: `sdns://user:password@sdnsstamp`.
