### ISSUE TITLE
Queries for `$denyallow`-ed domains are blocked

### ISSUE THREAD

**Issue by sxgunchenko** [AdguardTeam/DnsLibs#192]
STR:
1) Add the rule: `/^(.+[_.-])?partners?([\d]+)?[_.-]/$denyallow=api-partner.spotify.com`.
2) Run `dig api-partner.spotify.com` - it must be successfully resolved, but it is not.

**Comment by grumaxxx** [comment]
The following rule may be used in this case:
`/^(.+[_.-])?partners?([\d]+)?[_.-]/$denyallow=api-partner.spotify.com|partners.wg.spotify.com
`
