### ISSUE TITLE
Match CNAME records against the blocklists

### ISSUE THREAD

**Issue by szolin** [AdguardTeam/DnsLibs#22]
See AGH feature:
https://github.com/AdguardTeam/AdGuardHome/issues/1185

> Here's what we should do:
> 1. Match CNAME records against the blocklists
> 2. Indicate in the query log that the response was blocked by matching a CNAME. It'd be ideal if we print the original response there as well.
> 3. Please note, that if there's an exception rule matching the DNS query's question, you should not check the CNAME.

**Comment by TPS** [comment]
Whenever implemented here, does that directly improve, e.g., AG-Android, or does this need filed in CoreLibs for that?

**Comment by sfionov** [comment]
@TPS No, AG for Android now use AdguardTeam/dnsproxy.

This project is C++ implementation on AdGuard's DNS filtering, which consumes less memory and will replace AdguardTeam/dnsproxy on some platforms.

**Comment by TPS** [comment]
I've noticed this a while ago as a problem on AG Android, yet I don't see the equivalent issue @ https://github.com/AdguardTeam/dnsproxy/issues _&/or_ https://github.com/AdguardTeam/AdguardForAndroid/issues .  Could such be done to track/implement this in that?  I'd be very interested in testing it.

**Comment by ameshkov** [comment]
Yeah, it will be implemented in dnsproxy as well.

Also, eventually, DnsLibs will replace dnsproxy on Android.

**Comment by TPS** [comment]
Is there a tracking issue for the Android implementation?

**Comment by ameshkov** [comment]
Not yet, but expect it to be done in v3.3

**Comment by ngorskikh** [comment]
dns-libs/pull-requests/48
