### ISSUE TITLE
DNS stamps for h3:// scheme and basic authentication

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/DnsLibs#221]
Hello,

can we use somehow DNS stamps for h3:// scheme and basic authentication at the same time? How I can generate it?🤔

Thank you.
Best regads!

**Comment by sfionov** [comment]
@ammnt basic auth in supported for sdns:// urls too, just add `user:pass@` before stamp hash.

**Comment by ammnt** [comment]
@sfionov, what about h3:// scheme? Can we generate sdns stamp for this?
