### ISSUE TITLE
DoH with h3:// scheme works unstable, https:// works fine

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/DnsLibs#229]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

7.18.1 (4778) (CL 1.15.55, DL 2.5.33 )

### Browser version

Firefox 131.0 (64-разрядный)

### OS version

Windows 11 23H2

### Issue Details

Steps to reproduce:
1. Install AdGuard for Windows
2. Install AdGuard VPN for Windows
3. Add your own DoH server with h3:// scheme
4. Test it

### Expected Behavior

DNS resolving will be more stable and faster

### Actual Behavior

DNS resolving is unstable. SERVFAIL error in logs etc.

### Screenshots

<details><summary>Screenshot 1</summary>

![2024-10-09_00-00-03](https://github.com/user-attachments/assets/4d0e02ae-436d-4d9d-b88c-301d7eb26989)

</details>

### Additional Information

Verbose logs from app and VPN + exported settings will be sent to devteam@adguard.com

**Comment by ammnt** [comment]
Logs has been sent just now. Support ticket: 964926.

**Comment by ammnt** [comment]
Same behavior with android applications.

**Comment by ammnt** [comment]
So? Anyone?...

**Comment by sfionov** [comment]
@ammnt Issue should be fixed in the latest AdGuard VPN nightly version 2.4.1601.0

**Comment by ammnt** [comment]
@sfionov, I have AdGuard VPN version 2.5.0 (1652) now and nothing changed. Same unstable behavior. Has this fix been implemented?

**Comment by ammnt** [comment]
Up. Still not fixed👎
