### ISSUE TITLE
Refactor bootstrapper

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/DnsLibs#23]
1) There should be convenient way to create bootstrapper from url (?) and options (including ipv6 availability)
2) Both DoT and DoH should use bootstrapper.get() for every request.
    For DoH there should be a method to automatically convert it to curl "resolved" entry passed to CURLOPT_RESOLVE.
3) m_round_robin should not advance automatically.
4) New method to report that server got from bootstrapper doesn't work. This advances m_round_robin.
5) DoH is creating bootstrapper itself. DoT doesn't.
    Please make bootstrap passable to DoH or make DoT create bootstrapper too.
6) ipv6_avail to dnsproxy_settings

**Comment by sxgunchenko** [comment]
dns-libs/pull-requests/33
