### ISSUE TITLE
filtering module does not use last rule from filter

### ISSUE THREAD

**Issue by IvanIin** [AdguardTeam/DnsLibs#25]
steps to reproduce:
1) add filter [Lenny_filter.txt](https://github.com/AdguardTeam/DnsLibs/files/3955550/Lenny_filter.txt)
to dns proxy
in logs you can see `[debug] unique domains table size: 2` (instead of 3)
2) try to resolve host 'yandex.ru' and get NXDOMAIN as a result - it is good
3) try to resolve host 'meduza.io'

expected result:
NXDOMAIN

actual result:
resolved ip address

**Comment by sxgunchenko** [comment]
dns-libs/pull-requests/40
