### ISSUE TITLE
Enhance rule validation

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/DnsLibs#33]

**Comment by sxgunchenko** [comment]
The following things have to be done here:
1) Allow rules to contain in domain-part:
    - only one of the following prefixes: `://`, `http(s)://`, `ws(s)://` (e.g. `||http://example.com`)
    - only one of the following suffixes: `/`, `:<port_number>` (e.g. `example.com/|`)
2) Discard rules which contain anything except allowed in prefix or suffix (e.g. for now the rule `example.com/something` is considered valid), or anything before/after special prefixes/suffixes (e.g. `example^something`)
3) Ensure that `://`, `http(s)://` and `ws(s)://` work as if rule starts with `||`. If not, make it so

**Comment by sxgunchenko** [comment]
dns-libs/pull-requests/54
