### ISSUE TITLE
[Android] Wrong filter ID in DnsRequestProcessedEvent

### ISSUE THREAD

**Issue by admitrevskiy** [AdguardTeam/DnsLibs#38]
Steps to reproduce:

- Specify 2 filters. In my case it's AG SDN filter (ID == 15) and tiny custom filter with only one rule: `0.0.0.0 example.com` (ID == -3)
- Try to resolve `example.com`
- Filter ID in DnsRequestProcessedEvent is wrong
```
... bytesSent=0, bytesReceived=0, rules=[0.0.0.0 example.com], filterListIds=[15], whitelist=false...
```

**Comment by ngorskikh** [comment]
dns-libs/pull-requests/64
