### ISSUE TITLE
Add upstreams sorting by RTT

### ISSUE THREAD

**Issue by admitrevskiy** [AdguardTeam/DnsLibs#39]
Please, add upstreams sorting (by analogy with [dnsproxy](https://github.com/AdguardTeam/dnsproxy))

It may be useful in the following case:

There are several upstreams specified by the user. For example:
```
1.2.3.4
5.6.7.8
9.10.11.12
1.1.1.1
```

The first three are not valid and the user will wait for the timeout of each of them for each request.

Upstream `1.1.1.1`  will get to the beginning after sorting  `from fast to slow`.

**Comment by ngorskikh** [comment]
261a86ed914e4d844a01cafb6ef0b36b9bcc7631
