### ISSUE TITLE
Add the option to select blocking type

### ISSUE THREAD

**Issue by admitrevskiy** [AdguardTeam/DnsLibs#40]
Please, add ability to select blocking type by analogue with go-dnsproxy and AG Home

There are several options:
- Default
`||example.com^` rule should block both A and AAAA requests to `example.com` with NXDomain
`0.0.0.0 example.com` rule should block both A and AAAA requests to `example.com` with `unspecified ip (0.0.0.0 or [::])` response
`1.2.3.4` example.com should be used only for A requests to `example.com`

- NXDomain
`||example.com^`, `0.0.0.0 example.com` should block both A and AAAA requests with `NXDomain`

- Unspecified IP
`||example.com^`, `0.0.0.0 example.com` should block both A and AAAA requests with `unspecified ip (0.0.0.0 or [::])` response

**Comment by sfionov** [comment]
> 1.2.3.4 example.com should be used only for A requests to example.com

Current `/etc/hosts` logic differs, if there is any host rule with specific IP, only this set of IPs will be used to resolve both IPv4 and IPv6 addresses.

So if `/etc/hosts` are:
```
1.2.3.4 example.org
```
A will return 1.2.3.4
AAAA will return no addresses, request will not be forwarded.
If `/etc/hosts` are:
```
1.2.3.4 example.org
1234::5678 example.org
```
A will return 1.2.3.4
AAAA will return 1234::5678

I think we should use this logic for specific IPs in host rules.

**Comment by ameshkov** [comment]
Please do it as explained here:
https://github.com/AdguardTeam/AdGuardHome/issues/1284#issuecomment-573011150

**Comment by sfionov** [comment]
So we should threat both "0.0.0.0" and "127.0.0.1" hosts records as blocking

**Comment by ngorskikh** [comment]
dns-libs/pull-requests/60
