### ISSUE TITLE
White-list rule is ignored when matching CNAME 

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/DnsLibs#41]
Check this out:

![image](https://user-images.githubusercontent.com/5947035/72250872-b3f6eb80-360d-11ea-9244-865b0da12541.png)

We must not have blocked it due to this rule:
https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/Filters/exceptions.txt#L45

**Comment by sxgunchenko** [comment]
dns-libs/pull-requests/58
