### ISSUE TITLE
Add the ability to block dns requests by IP address

### ISSUE THREAD

**Issue by IvanIin** [AdguardTeam/DnsLibs#44]

**Comment by ameshkov** [comment]
Just like matching CNAME, we should be able to match IP addresses in A/AAAA records.

**Comment by ngorskikh** [comment]
Any suggestions on the syntax for IP-blocking rules? As it is, both `1.2.3.4` and `12:34::56` forms will simply fail to parse.

**Comment by ameshkov** [comment]
What do you mean, there's no special syntax, you just match against IP addresses in its string format.

**Comment by ngorskikh** [comment]
dns-libs/pull-requests/72
