### ISSUE TITLE
Domain 'www.example.org' matched against rule '|example.org^'

### ISSUE THREAD

**Issue by IvanIin** [AdguardTeam/DnsLibs#45]
how to reproduce:
 - add rule ' |example.org^' to domains filter
 - request 'www.example.org'

expected result:
 dnslibs returns the correct answer

actual result:
dnslibs returns NXDOMAIN

**Comment by ngorskikh** [comment]
@sfionov @sxgunchenko is this a bug, though? Currently, `any.subdomain.of.example.org` will match the rule `example.org` and that logic is explicit (we generate a list of hostname substrings, successively removing the last subdomain until reaching the form `domain.tld`, and then repeatedly match the substrings against against an "exact domain" rule)

**Comment by ameshkov** [comment]
`|` means the beginning of a string so yes, this is a bug.

**Comment by ngorskikh** [comment]
dns-libs/pull-requests/72
