### ISSUE TITLE
Add memory usage limit on iOS

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/DnsLibs#56]
To not to crash on large filters (like Ultimate hosts blocklist).
We have two options here:
- Stop loading rules after reaching the limit, init returns non-fatal error.
- Stop loading rules after reaching the limit, init returns fatal error.

**Comment by ngorskikh** [comment]
Question: how should memory usage be measured: do we 
1. count the total memory allocated while loading the filters, OR 
2. periodically check the current RSS and stop if the delta between now and before loading any filters reaches a certain value?

**Comment by ngorskikh** [comment]
dns-libs/pull-requests/93
