### ISSUE TITLE
Vpn constantly crashes if add Base filter

### ISSUE THREAD

**Issue by zzebrum** [AdguardTeam/DnsLibs#57]
Add [Base filter](https://filters.adtidy.org/extension/chromium/filters/2.txt) as DNS requests blocking list --> VPN constantly crashes.

**Comment by ngorskikh** [comment]
Can't repro, need more data. Asked @08kovalchuk03 to repro on iOS -- no crashes. Measured the network extension memory usage with base filter: 4.6MB, so this shouldn't be a memory issue.
