### ISSUE TITLE
Check if the rule is a domain name and use exact matching for it in this case

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/DnsLibs#66]
Check how it's done in urlfilter:
https://github.com/AdguardTeam/urlfilter/blob/master/rules/host_rule.go#L50

**Comment by lancelot-moon** [comment]
Your designed logic for only domain list in AG for Android/iOS may cause the issue:
https://github.com/AdguardTeam/AdguardForAndroid/issues/3390

**Comment by lancelot-moon** [comment]
Except for domain, CNAME will be also blocked.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/QXAUafN.png)

![image](https://i.imgur.com/z75GqCp.png)
</details><br/>

**Comment by lancelot-moon** [comment]
1. AG for iOS v4 beta with anti-AD domains list for the DNS filter.
https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-domains.txt

Got the proofs.
Due to the designed logic, githubusercontent.com is wrongly blocked by the domain rule, ntent.com.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/nJcUxSn.jpg)

![image](https://i.imgur.com/s2YNdHe.jpg)
</details><br/>

Need to redesign the logic for only domain list.

2. Does this issue also happen in custom HTTPS filters with only domain list?

**Comment by lancelot-moon** [comment]
I tried subscribing to the domains list in the custom HTTPS filters subscriptions of AG for Windows.
The same problematic logic is also for HTTPS filters with domains list.
githubusercontent.com is wrongly blocked on HTTPS level by the domain rule, ntent.com.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/JuMoOss.png)
</details><br/>

I don't know where to open the issue.
CoreLibs?

**Comment by lancelot-moon** [comment]
I tried subscribing to the domains list in the custom HTTPS filters subscriptions of AG Browser Extension.
The same problematic logic causes the incorrect blocking.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/f2JLIBj.png)
</details><br/>

**Comment by lancelot-moon** [comment]
Hi,
Maybe it's time to define filter patterns of domain format which AG team didn't pay attention to in the past.
https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Filters

Some filter patterns:
`example.com` - identical to the above
`*.example.com` - block example.com and its sub-domains
`=example.com` - only block example.com, not include its sub-domains
`*example.com` - matches any name containing that substring

**I'm not sure if the definitions of `example.com` and `=example.com` are the same in its wiki.
May you answer me? Thanks.**

In this case:
`ntent.com` - only block ntent.com? Its sub-domains?
`*.ntent.com` - block ntent.com and its sub-domains
`=ntent.com` - only block ntent.com, not include its sub-domains
`*ntent.com` - block the domains which match any name containing ntent.com

ex:
If `ntent.com` is in the domains list, only `ntent.com` is blocked, but `githubusercontent.com` and the sub-domains of `ntent.com` aren't blocked.
If `*ntent.com` is in the domains list, both `ntent.com` and `githubusercontent.com` are blocked.

**Comment by ameshkov** [comment]
You don't have to open an issue in AG4W, it works exactly as it should.

> Maybe it's time to define filter patterns of domain format which AG team didn't pay attention to in the past.

I see no sensible reason to support other types of syntax.

We support /etc/hosts and domains lists merely because of their popularity, but we do not want to encourage using them or maintaining hosts lists that use that syntax.

There is only one type of syntaxes that we encourage everyone to use:
https://github.com/AdguardTeam/AdGuardHome/wiki/Hosts-Blocklists#adblock-style
