### ISSUE TITLE
Deep CNAME inspection is supported, right?

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/DnsLibs#67]
I read this:
https://pi-hole.net/2020/01/19/announcing-a-beta-test-of-pi-hole-5-0/#page-content
Deep CNAME inspection
This has been a covered in a broadly discussed feature request  for the ability to deeply analyze CNAME queries. This will allow FTL to find whether any intermediate domain in the chain is known to be blocked. If one is found, Pi-hole can now block the entire query and returns an empty reply to the requesting client. As this is a very work-intense process, it may lead to notable delays if you run Pi-hole on a very low end device such as the Pi Zero with a large number of clients. The feature defaults to being enabled but can be disabled with an FTL config option (CNAME_DEEP_INSPECT=false).

In my test about the DNS filtering of AG for Android, a matched domain in CNAME will be also blocked, except for the domain.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/QXAUafN.png)

![image](https://i.imgur.com/z75GqCp.png)
</details><br/>

Deep CNAME inspection is supported in AG for Android, right?
AG Pro for iOS v2 shouldn't support this yet.
Is this supported in AG for iOS v4 and AG Home?
Just wish a clarification.

**Comment by ameshkov** [comment]
Sure we do that in every product that provides DNS filtering.
