### ISSUE TITLE
Update Cloudflare DNS servers.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/DnsLibs#68]
https://blog.cloudflare.com/introducing-1-1-1-1-for-families/

Add these:
Malware Blocking Only
Primary DNS: 1.1.1.2
Secondary DNS: 1.0.0.2

Malware and Adult Content
Primary DNS: 1.1.1.3
Secondary DNS: 1.0.0.3

For IPv6 use:

Malware Blocking Only
Primary DNS: 2606:4700:4700::1112
Secondary DNS: 2606:4700:4700::1002

Malware and Adult Content
Primary DNS: 2606:4700:4700::1113
Secondary DNS: 2606:4700:4700::1003

**Comment by ameshkov** [comment]
@vozersky we should replicate this to product repos + KB, then close it here.

**Comment by lancelot-moon** [comment]
KB:
https://kb.adguard.com/en/general/dns-providers#cloudflare-dns

**Comment by vozersky** [comment]
task for kb update: https://github.com/AdguardTeam/AdguardKnowledgeBase/issues/486

**Comment by lancelot-moon** [comment]
Will you not add these in the default DNS providers of AG for Android/iOS?

**Comment by vozersky** [comment]
@lancelot-moon Will do! Also DNS settings for Windows are coming soonish
