### ISSUE TITLE
Incorrect behavior of DNS User filter

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/DnsLibs#72]
### Issue Details

Rules of this type do not apply after updates to the beta version:
![image](https://user-images.githubusercontent.com/49645813/80859474-fea67d00-8c69-11ea-8d3b-3be5aca546a9.png)

- **AdGuard version:**
  - 3.4 beta 1  (98-1.5.249cl)
- **Filtering mode:**
  -  VPN
- **Operating system and version:**
  -  Android 9
- **Root access:**
  -  No

**HelpDesk ID**: 2576359

**Comment by sfionov** [comment]
Test
