### ISSUE TITLE
Check if we should block SVCB (type 65, service binding?) records

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/DnsLibs#80]
iOS 14 generates many such records. We need to investigate what functionality of SVCB records is used in iOS 14

**Comment by jordanelliott23** [comment]
it looks like sometimes it blocks type65 but sometimes it doesnt. example attached
![Uploading ECE7187D-F522-4E7E-A398-72594F6037BD.png…]()

**Comment by jordanelliott23** [comment]
![FE382038-8D18-47C0-BC73-7CCF4D0DDEF9](https://user-images.githubusercontent.com/71462072/94350047-01867d80-0010-11eb-8ce6-54a73167e19f.png)

**Comment by jordanelliott23** [comment]
@ameshkov

**Comment by ameshkov** [comment]
Weird stuff. We definitely should block TYPE65 when DNS is blocked.

This, btw, is true for AdGuard DNS and AdGuard Home as well.

**Comment by jordanelliott23** [comment]
> Weird stuff. We definitely should block TYPE65 when DNS is blocked.
> 
> This, btw, is true for AdGuard DNS and AdGuard Home as well.

is it a easy fix? hopefully. because ive been seen alot of type65 unblocked in my log lately.

**Comment by ngorskikh** [comment]
@jordanelliott23 could you please check to see if your filters actually contain some rules matching the domains from those unblocked TYPE65 requests? It could be that A/AAAA requests are actually blocked by matching a CNAME in the response.

**Comment by jordanelliott23** [comment]
> @jordanelliott23 could you please check to see if your filters actually contain some rules matching the domains from those unblocked TYPE65 requests? It could be that A/AAAA requests are actually blocked by matching a CNAME in the response.



> @jordanelliott23 could you please check to see if your filters actually contain some rules matching the domains from those unblocked TYPE65 requests? It could be that A/AAAA requests are actually blocked by matching a CNAME in the response.

sorry i don't understand what you mean by that.

**Comment by jordanelliott23** [comment]
@ngorskikh sorry i don't understand

**Comment by jordanelliott23** [comment]
@ngorskikh here is an attached example of what i think your trying to ask. the domain thats being blocked in this screenshot is located in adguard simplified domains filter. it doesnt block the type65 request one so ill attach all needed/helpful screenshots

**Comment by jordanelliott23** [comment]
![100DDFEB-F900-47C4-9658-638987DBA790](https://user-images.githubusercontent.com/71462072/94477080-00cc2380-0197-11eb-8025-616477079992.png)
![CBF537BA-953E-484E-ABEE-7ACBCE270BEA](https://user-images.githubusercontent.com/71462072/94477085-0295e700-0197-11eb-9a39-a0b5ff75daf4.jpeg)

**Comment by jordanelliott23** [comment]
my question is why type65 blocked sometimes and sometimes it isnt. 
![FA2D37FF-EEB2-4E6E-948D-1DBE43605568](https://user-images.githubusercontent.com/71462072/94478510-fdd23280-0198-11eb-9a9e-a482d712acaf.jpeg)

**Comment by ngorskikh** [comment]
@jordanelliott23 
Let me explain. `scripttags.jst.ai` is *not* actually in the AdGuard Simplified Domain names filter. You can verify that by looking through the filter itself: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

Now, your A and AAAA (IPv4 and IPv6) queries for `scripttags.jst.ai` are being blocked because the response to those queries contains a CNAME:
 ```
scripttags.jst.ai.      161     IN      CNAME   scripttags.justuno.com.
``` 
which *is* matched by the rule `||justuno.com^`. TYPE65 queries are not blocked because they don't match any rule in the filter and there's no CNAME in the response to try to match that.

On your second screenshot, all queries for `agkn.com` are matched by the rule `||agkn.com^` and are blocked, accordingly.

**Comment by jordanelliott23** [comment]
ok i understand that. but privacy-policy.truste.com is located in that list and the type65 version isnt blocked 
![9EE60F50-5E49-43EA-9B3A-CE6BD2E557C0](https://user-images.githubusercontent.com/71462072/94482913-a5526380-019f-11eb-923a-516ff838fe9e.jpeg)

**Comment by ngorskikh** [comment]
That is weird, indeed. I've checked the library behavior for these two rules:
```
||privacy-policy.truste.com^
||agkn.com^
```
and it is identical, and, as far as I can see, valid. Both queries are blocked with an empty response with a fake SOA record. Albeit, the RCODE is **NOERROR** instead of **NXDOMAIN** (which is in line with the behavior of major public DNS resolvers). 
Still, this doesn't explain the apparent difference in how these queries are presented in the filtering log. This could simply be a UI issue.

Another possibility is that there's some other filter that unblocks `privacy-policy.truste.com` with an exception rule, but A/AAAA quries are still blocked by CNAME: `privacy-policy.truste.com. 209  IN      CNAME   d2pj9rkatqbt38.cloudfront.net.`

**Comment by jordanelliott23** [comment]
yeah i don't understand what exactly is happening here is another example, collector-pxuarm9b04.perimeterx.net type65 request isnt blocked and its in the domain filter list
![3C9DC7F6-F1E6-4F5A-A589-C4B80C8202A2](https://user-images.githubusercontent.com/71462072/94491333-a4c0c980-01ad-11eb-96f3-b4e8e8cd5207.jpeg)

**Comment by Chinaski1** [comment]
Hello @jordanelliott23 

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Reproduce the issue (and remember the exact time when it happened);
2. Disable "DNS Privacy";
3. Open the settings(Gear), tap "Send Feedback", select "Contact Support";
3. The mail app will be opened, **change the recipient to `apple@adguard.com` (!)**;
4. Mention this issue number in the email text.

**Comment by jordanelliott23** [comment]
So guys I figured it out. There was a type65 domain that is in the AdGuard dns filter list that wasn’t blocked until I added the filter list to my app. So what this means is that the AdGuard dns itself in general meaning if someone just used the dns servers without the app it does not block type65. How can that be fixed? It’s definitely not a User interface bug it has to do with AdGuard servers not blocking type65 requests. Glad I could figure it out. @Chinaski1  @ngorskikh  @ameshkov  @sfionov

**Comment by ngorskikh** [comment]
Pretty strange that a blocking problem was reported here when no filters are in use, i.e. DnsLibs doesn't do anything :)
It is, though, on the contrary, looks very much like a UI bug: let's examine AdGuard DNS behaviour:
```
➜  ~ dig @94.140.14.14 privacy-policy.truste.com -t TYPE65

; <<>> DiG 9.10.6 <<>> @94.140.14.14 privacy-policy.truste.com -t TYPE65
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 64749
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;privacy-policy.truste.com.	IN	TYPE65

;; AUTHORITY SECTION:
privacy-policy.truste.com. 3600	IN	SOA	fake-for-negative-caching.adguard.com. hostmaster.privacy-policy.truste.com. 100500 1800 900 604800 86400

;; Query time: 72 msec
;; SERVER: 94.140.14.14#53(94.140.14.14)
;; WHEN: Fri Oct 16 22:00:11 MSK 2020
;; MSG SIZE  rcvd: 135

➜  ~ dig @1.1.1.1 privacy-policy.truste.com -t TYPE65

; <<>> DiG 9.10.6 <<>> @1.1.1.1 privacy-policy.truste.com -t TYPE65
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34283
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;privacy-policy.truste.com.	IN	TYPE65

;; ANSWER SECTION:
privacy-policy.truste.com. 319	IN	CNAME	d2pj9rkatqbt38.cloudfront.net.

;; AUTHORITY SECTION:
d2pj9rkatqbt38.cloudfront.net. 619 IN	SOA	ns-550.awsdns-04.net. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 9 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Fri Oct 16 22:00:18 MSK 2020
;; MSG SIZE  rcvd: 175
```
Looks like AdGuard DNS properly blocks the TYPE65 request by returning an empty NXDOMAIN with a fake SOA record, but this fact is not highlighted in the UI.
@jordanelliott23 sorry to go bureaucratic, but you should probably file a report in https://github.com/AdguardTeam/AdguardForiOS/issues with a link to this discussion :)

**Comment by jordanelliott23** [comment]
@ngorskikh the ipv4 and ipv6 show blocked though because I use the AdGuard dns in the dns protection part. But type65 doesn’t block til I ad the filter list. Kinda confusing to explain I hope that makes sense.
