### ISSUE TITLE
Retry DoQ/DoH/DoT queries

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/DnsLibs#86]
It is pretty normal for a server to close connection when the client does not expect it.

Currently, the DnsLibs logic is to use the fallback. Ideally, we should make one more try before using the fallback. But don't forget to check if the timeout is expired.

**Comment by wanesoft** [comment]
dns-libs/pull-requests/181

**Comment by wanesoft** [comment]
dns-libs/pull-requests/187

**Comment by wanesoft** [comment]
dns-libs/pull-requests/189
