### ISSUE TITLE
Allow persisting the DNS cache

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/DnsLibs#95]
This is quite important on mobile devices since they often change networks and this triggers new DNS queries.
Persisting DNS cache would allow us to save quite a lot.

However, we should also allow:
1. Easily clearing this (API? or just removing the file?).
2. This feature should be optional.

**Comment by ngorskikh** [comment]
@ameshkov Shouldn't we flush the cache on network change anyway?

**Comment by ameshkov** [comment]
@ngorskikh what's important is whether the upstream DNS server changed. If it didn't then we can reuse the cache.

**Comment by sfionov** [comment]
@ameshkov I think, if upstream server is anycast or use ECS, resolve result may be different after network change even with the same upstream.

**Comment by ameshkov** [comment]
@sfionov well, yes, but would it cause any issues? I honestly doubt it.

The question is how much would the savings be if we employ a persistent cache (ideally -- persistent + optimistic caching).
Can we run a simple experiment on an Android device and see what the savings are?
