### ISSUE TITLE
Looking to integrate the DnsLibs as a lib.so or static library to C code.

### ISSUE THREAD

**Issue by dwdrajesh** [AdguardTeam/DnsLibs#96]
Hi, I am looking to use the DNS over QUIC feature on my app that is in C. Unfortunately, we do not have C++ support yet and so I was wondering if there is a way to build the DnsLibs library into a static or dynamic library and to call the DnsLibs api from my app by copying over the DnsLibs library to my source code directory. Of course, it is just an experimental way to test and won't go into any production code. Any documentation on that? Please note this is for native Linux environment. The developer guide below only talks about using the DnsLibs code directly. Would appreciate any help. 

https://github.com/AdguardTeam/DnsLibs/blob/master/documentation/DEV_DOCS.en.md

Thanks,
Rajesh

**Comment by dwdrajesh** [comment]
Any idea @TimusBel , @ngorskikh  please. Thanks

**Comment by ngorskikh** [comment]
@dwdrajesh There's a C wrapper in `platform/windows/capi`. It should build an .so on Linux or .dylib on macOS. It is intended for C# interop, but could be used directly from C just as well :)

**Comment by dwdrajesh** [comment]
Hi, 

> @dwdrajesh There's a C wrapper in `platform/windows/capi`. It should build an .so on Linux or .dylib on macOS. It is intended for C# interop, but could be used directly from C just as well :)

Thanks. Actually I was looking at how to build a static (.a) library since that would make things a bit easier for testing now, any instructions on that for Linux or if you have tried that please? Thanks

**Comment by dwdrajesh** [comment]
> Hi,
> 
> > @dwdrajesh There's a C wrapper in `platform/windows/capi`. It should build an .so on Linux or .dylib on macOS. It is intended for C# interop, but could be used directly from C just as well :)
> 
> Thanks. Actually I was looking at how to build a static (.a) library since that would make things a bit easier for testing now, any instructions on that for Linux or if you have tried that please? Thanks

Hi, Could you please provide pointers on how to build a static library (.a) and to build it for on Linux (Ubuntu, debian) machine for Linux x86_64 please? Thanks @ngorskikh @TimusBel thanks please
