### ISSUE TITLE
Update DoQ support to draft-ietf-dprive-dnsoquic-02

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/DnsLibs#97]
The most problematic change there is the change of the default port (it is now 8853).

When we start using the new DnsLibs version in our products, we'll have to update the default port to 784 as well, i.e. for all **custom** upstreams, we'll have to change `quic://example.org` to `quic://example.org:784`.

Check the changes:
https://github.com/AdguardTeam/dnsproxy/pull/128

**Comment by wanesoft** [comment]
dns-libs/pull-requests/209
